-- DELIMITER $$
-- 
-- CREATE PROCEDURE test_proc (
-- 	IN in_num INT )
-- -- 	, OUT )
-- BEGIN
--     SELECT * FROM employees LIMIT in_num;
-- END $$
-- 
-- DELIMITER ;

-- CALL test_proc(10); 

-- DELIMITER $$
-- 
-- CREATE FUNCTION fc_sum (num INT)
-- 	RETURNS INT
-- BEGIN
--     RETURN num + num + num;
-- END $$
-- 
-- DELIMITER ;
-- 
-- SELECT fc_sum(3);